name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-D warnings"

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint, test, and package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

      - name: Doctests
        run: cargo test --workspace --all-features --doc --locked

      - name: Unit tests
        run: cargo test --workspace --all-targets --all-features --locked

      - name: Documentation build
        run: cargo doc --workspace --all-features --no-deps --locked

      - name: Package validation
        run: cargo package --locked
