name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build and publish release assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Tests (release)
        run: cargo test --workspace --all-targets --all-features --release

      - name: Package crate
        run: cargo package --locked

      - name: Build release binaries
        run: cargo build --release --locked --bin grid_demo

      - name: Collect artifacts
        run: |
          mkdir -p dist
          BIN_NAME="grid_demo-${{ github.ref_name }}"
          cp target/release/grid_demo "dist/${BIN_NAME}"
          tar -czf "dist/${BIN_NAME}-x86_64-unknown-linux-gnu.tar.gz" -C dist "${BIN_NAME}"
          rm "dist/${BIN_NAME}"
          cp target/package/*.crate dist/
          sha256sum dist/* > dist/SHA256SUMS.txt

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/*.tar.gz
            dist/*.crate
            dist/SHA256SUMS.txt
